export default {
  THEME_CHANGE: "THEME_CHANGE",
  THEME_INIT: "THEME_INIT",
  POPULAR_REFRESH: 'POPULAR_REFRESH', // 列表数据刷新
  LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL',  // 列表数据加载失败
  LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS',  // 列表数据加载成功
}
