export default {
  THEME_CHANGE: "THEME_CHANGE",
  THEME_INIT: "THEME_INIT",
  POPULAR_REFRESH: 'POPULAR_REFRESH', // 列表数据刷新
  // LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL',  // 列表数据加载失败
  // LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS',  // 列表数据加载成功
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', //
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',

  TRENDING_REFRESH: 'TRENDING_REFRESH', // 列表数据刷新
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', //
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',
}
